//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCelmiPecuaria.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppCelmiPecuaria.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:d} selecionados.
        /// </summary>
        internal static string _0DSelecionados {
            get {
                return ResourceManager.GetString("_0DSelecionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        internal static string Adicionar {
            get {
                return ResourceManager.GetString("Adicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Campo Personalizado.
        /// </summary>
        internal static string AdicionarCampoPersonalizado {
            get {
                return ResourceManager.GetString("AdicionarCampoPersonalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguardando.
        /// </summary>
        internal static string Aguardando {
            get {
                return ResourceManager.GetString("Aguardando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguarde....
        /// </summary>
        internal static string Aguarde {
            get {
                return ResourceManager.GetString("Aguarde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguarde... Conectando....
        /// </summary>
        internal static string AguardeConectando {
            get {
                return ResourceManager.GetString("AguardeConectando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Nome.
        /// </summary>
        internal static string Alterar {
            get {
                return ResourceManager.GetString("Alterar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automotivo.
        /// </summary>
        internal static string AppCelmiAuto {
            get {
                return ResourceManager.GetString("AppCelmiAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviação.
        /// </summary>
        internal static string AppCelmiAviação {
            get {
                return ResourceManager.GetString("AppCelmiAviação", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sementes.
        /// </summary>
        internal static string AppCelmiEnsaioDeCampo {
            get {
                return ResourceManager.GetString("AppCelmiEnsaioDeCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geral.
        /// </summary>
        internal static string AppCelmiGeral {
            get {
                return ResourceManager.GetString("AppCelmiGeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máquinas Agrícolas.
        /// </summary>
        internal static string AppCelmiMáquinas {
            get {
                return ResourceManager.GetString("AppCelmiMáquinas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pecuária.
        /// </summary>
        internal static string AppCelmiPecuária {
            get {
                return ResourceManager.GetString("AppCelmiPecuária", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área medida.
        /// </summary>
        internal static string AreaMedida {
            get {
                return ResourceManager.GetString("AreaMedida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área Medida.
        /// </summary>
        internal static string ÁreaMedida {
            get {
                return ResourceManager.GetString("ÁreaMedida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo de Backup Inválido.
        /// </summary>
        internal static string ArquivoDeBackupInválido {
            get {
                return ResourceManager.GetString("ArquivoDeBackupInválido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arroba (médio).
        /// </summary>
        internal static string ArrobaMédio {
            get {
                return ResourceManager.GetString("ArrobaMédio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrobas.
        /// </summary>
        internal static string Arrobas {
            get {
                return ResourceManager.GetString("Arrobas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arroba (total).
        /// </summary>
        internal static string ArrobaTotal {
            get {
                return ResourceManager.GetString("ArrobaTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A TARA foi Ativada!.
        /// </summary>
        internal static string ATARAFoiAtivada {
            get {
                return ResourceManager.GetString("ATARAFoiAtivada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A TARA foi Desativada!.
        /// </summary>
        internal static string ATARAFoiDesativada {
            get {
                return ResourceManager.GetString("ATARAFoiDesativada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Lista Pesagens.
        /// </summary>
        internal static string BackupListaPesagens {
            get {
                return ResourceManager.GetString("BackupListaPesagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balança.
        /// </summary>
        internal static string Balança {
            get {
                return ResourceManager.GetString("Balança", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bastão ALLTAGS.
        /// </summary>
        internal static string BastaoAllTAGS {
            get {
                return ResourceManager.GetString("BastaoAllTAGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bateria.
        /// </summary>
        internal static string Bateria {
            get {
                return ResourceManager.GetString("Bateria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bateria Carregando....
        /// </summary>
        internal static string BateriaCarregando {
            get {
                return ResourceManager.GetString("BateriaCarregando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você precisa estar com o Bluetooth ativado para usar esse aplicativo! Por favor ativar!.
        /// </summary>
        internal static string BluetoothLigado {
            get {
                return ResourceManager.GetString("BluetoothLigado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bruto.
        /// </summary>
        internal static string Bruto {
            get {
                return ResourceManager.GetString("Bruto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busca por dispositivos finalizada....
        /// </summary>
        internal static string BuscaPorDispositivosFinalizada {
            get {
                return ResourceManager.GetString("BuscaPorDispositivosFinalizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campos Padrão.
        /// </summary>
        internal static string CamposPadrão {
            get {
                return ResourceManager.GetString("CamposPadrão", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campos personalizados.
        /// </summary>
        internal static string CamposPersonalizados {
            get {
                return ResourceManager.GetString("CamposPersonalizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar Busca de Dispositivos.
        /// </summary>
        internal static string CancelarBuscaDeDispositivos {
            get {
                return ResourceManager.GetString("CancelarBuscaDeDispositivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carga Viva.
        /// </summary>
        internal static string CargaViva {
            get {
                return ResourceManager.GetString("CargaViva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celmi Sistemas de Pesagem - Relatório.
        /// </summary>
        internal static string CelmiSistemasDePesagemRelatório {
            get {
                return ResourceManager.GetString("CelmiSistemasDePesagemRelatório", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chassi.
        /// </summary>
        internal static string Chassi {
            get {
                return ResourceManager.GetString("Chassi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade/Localização.
        /// </summary>
        internal static string CidadeLocalização {
            get {
                return ResourceManager.GetString("CidadeLocalização", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        internal static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clique em PROCURAR para pesquisar por Dispositivos Próximos....
        /// </summary>
        internal static string CliqueEmPROCURARParaPesquisarPorDispositivosPróximos {
            get {
                return ResourceManager.GetString("CliqueEmPROCURARParaPesquisarPorDispositivosPróximos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando TARA Enviado.
        /// </summary>
        internal static string ComandoTARAEnviado {
            get {
                return ResourceManager.GetString("ComandoTARAEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando ZERO Enviado.
        /// </summary>
        internal static string ComandoZEROEnviado {
            get {
                return ResourceManager.GetString("ComandoZEROEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectado.
        /// </summary>
        internal static string Conectado {
            get {
                return ResourceManager.GetString("Conectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectado a Dispositivo CI.
        /// </summary>
        internal static string ConectadoADispositivoCI {
            get {
                return ResourceManager.GetString("ConectadoADispositivoCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectado a Dispositivo CSP-10A.
        /// </summary>
        internal static string ConectadoADispositivoCSP10A {
            get {
                return ResourceManager.GetString("ConectadoADispositivoCSP10A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectado ao Dispositivo RX.
        /// </summary>
        internal static string ConectadoADispositivoRX {
            get {
                return ResourceManager.GetString("ConectadoADispositivoRX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectando.
        /// </summary>
        internal static string Conectando {
            get {
                return ResourceManager.GetString("Conectando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectando Impressora :.
        /// </summary>
        internal static string ConectandoImpressora {
            get {
                return ResourceManager.GetString("ConectandoImpressora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectar Parcial.
        /// </summary>
        internal static string ConectarParcial {
            get {
                return ResourceManager.GetString("ConectarParcial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexão Bluetooth.
        /// </summary>
        internal static string ConexãoBluetooth {
            get {
                return ResourceManager.GetString("ConexãoBluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexão por Plataforma.
        /// </summary>
        internal static string ConexãoPorPlataforma {
            get {
                return ResourceManager.GetString("ConexãoPorPlataforma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite Conexão em Plataformas Individuais.
        /// </summary>
        internal static string ConexaoPorPlataformas {
            get {
                return ResourceManager.GetString("ConexaoPorPlataformas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite conexões em plataformas individuais. Utilize essa opção se você não tiver um visor RX e deseja conectar diretamente nas plataformas.  .
        /// </summary>
        internal static string ConexaoPorPlataformasDesc {
            get {
                return ResourceManager.GetString("ConexaoPorPlataformasDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIGURAÇÕES.
        /// </summary>
        internal static string CONFIGURAÇÕES {
            get {
                return ResourceManager.GetString("CONFIGURAÇÕES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        internal static string ConfiguraçõesCamelCase {
            get {
                return ResourceManager.GetString("ConfiguraçõesCamelCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do ensaio.
        /// </summary>
        internal static string DadosDoEnsaio {
            get {
                return ResourceManager.GetString("DadosDoEnsaio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data/Hora.
        /// </summary>
        internal static string DataHora {
            get {
                return ResourceManager.GetString("DataHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconectado.
        /// </summary>
        internal static string Desconectado {
            get {
                return ResourceManager.GetString("Desconectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconectando.
        /// </summary>
        internal static string Desconectando {
            get {
                return ResourceManager.GetString("Desconectando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconectar.
        /// </summary>
        internal static string Desconectar {
            get {
                return ResourceManager.GetString("Desconectar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconhecido.
        /// </summary>
        internal static string Desconhecido {
            get {
                return ResourceManager.GetString("Desconhecido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo importar essas pesagens?.
        /// </summary>
        internal static string DesejaMesmoImportarEssasPesagens {
            get {
                return ResourceManager.GetString("DesejaMesmoImportarEssasPesagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja substituir todas as pesagens pelas que estão sendo importadas ou adicionar novas?.
        /// </summary>
        internal static string DesejaSubstituirTodasAsPesagensPelasQueEstãoSendoImportadasOuAdicionarNovas {
            get {
                return ResourceManager.GetString("DesejaSubstituirTodasAsPesagensPelasQueEstãoSendoImportadasOuAdicionarNovas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivo TX - Encontrado(s).
        /// </summary>
        internal static string DispositivoTXEncontradoS {
            get {
                return ResourceManager.GetString("DispositivoTXEncontradoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eixo.
        /// </summary>
        internal static string Eixo {
            get {
                return ResourceManager.GetString("Eixo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eixo Dianteiro.
        /// </summary>
        internal static string EixoDianteiro {
            get {
                return ResourceManager.GetString("EixoDianteiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eixo Traseiro.
        /// </summary>
        internal static string EixoTraseiro {
            get {
                return ResourceManager.GetString("EixoTraseiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAILS DE CONTATO.
        /// </summary>
        internal static string EMAILSDECONTATO {
            get {
                return ResourceManager.GetString("EMAILSDECONTATO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário ativar o BLUETOOTH para procurar por dispositivos!.
        /// </summary>
        internal static string ÉNecessárioAtivarOBLUETOOTHParaProcurarPorDispositivos {
            get {
                return ResourceManager.GetString("ÉNecessárioAtivarOBLUETOOTHParaProcurarPorDispositivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar Comando.
        /// </summary>
        internal static string EnviarComando {
            get {
                return ResourceManager.GetString("EnviarComando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        internal static string Erro {
            get {
                return ResourceManager.GetString("Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espanhol.
        /// </summary>
        internal static string Espanhol {
            get {
                return ResourceManager.GetString("Espanhol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTE APLICATIVO.
        /// </summary>
        internal static string EsteAplicativo {
            get {
                return ResourceManager.GetString("EsteAplicativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        internal static string Excluir {
            get {
                return ResourceManager.GetString("Excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir Pesagens?.
        /// </summary>
        internal static string ExcluirPesagens {
            get {
                return ResourceManager.GetString("ExcluirPesagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fazenda/Propriedade.
        /// </summary>
        internal static string FazendaPropriedade {
            get {
                return ResourceManager.GetString("FazendaPropriedade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerar Relatório.
        /// </summary>
        internal static string GerarRelatório {
            get {
                return ResourceManager.GetString("GerarRelatório", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grão.
        /// </summary>
        internal static string Grão {
            get {
                return ResourceManager.GetString("Grão", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora.
        /// </summary>
        internal static string Hora {
            get {
                return ResourceManager.GetString("Hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horímetro.
        /// </summary>
        internal static string Horímetro {
            get {
                return ResourceManager.GetString("Horímetro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificação.
        /// </summary>
        internal static string Identificação {
            get {
                return ResourceManager.GetString("Identificação", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificação da Pesagem.
        /// </summary>
        internal static string IdentificaçãoDaPesagem {
            get {
                return ResourceManager.GetString("IdentificaçãoDaPesagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        internal static string Identificador {
            get {
                return ResourceManager.GetString("Identificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificar Pesagem.
        /// </summary>
        internal static string IdentificarPesagem {
            get {
                return ResourceManager.GetString("IdentificarPesagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No momento de salvar a pesagem é possível informar uma identificação para a pesagem (número do bag ou brinco do animal por exemplo). O valor é obtido nas pesagens salvas e nos relatórios..
        /// </summary>
        internal static string IdentificarPesagemDescv {
            get {
                return ResourceManager.GetString("IdentificarPesagemDescv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressora.
        /// </summary>
        internal static string Impressora {
            get {
                return ResourceManager.GetString("Impressora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir Bluetooth.
        /// </summary>
        internal static string ImprimirBluetooth {
            get {
                return ResourceManager.GetString("ImprimirBluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações.
        /// </summary>
        internal static string Informações {
            get {
                return ResourceManager.GetString("Informações", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Inglês {
            get {
                return ResourceManager.GetString("Inglês", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia Conexão.
        /// </summary>
        internal static string IniciaConexão {
            get {
                return ResourceManager.GetString("IniciaConexão", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ler com a câmera.
        /// </summary>
        internal static string LerComACâmera {
            get {
                return ResourceManager.GetString("LerComACâmera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Líquido.
        /// </summary>
        internal static string Líquido {
            get {
                return ResourceManager.GetString("Líquido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Pesagens.
        /// </summary>
        internal static string ListaDePesagens {
            get {
                return ResourceManager.GetString("ListaDePesagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localização.
        /// </summary>
        internal static string Localização {
            get {
                return ResourceManager.GetString("Localização", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logotipo.
        /// </summary>
        internal static string Logotipo {
            get {
                return ResourceManager.GetString("Logotipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs do Dispositivo.
        /// </summary>
        internal static string LogsDoDispositivo {
            get {
                return ResourceManager.GetString("LogsDoDispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs Globais.
        /// </summary>
        internal static string LogsGlobais {
            get {
                return ResourceManager.GetString("LogsGlobais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        internal static string Marca {
            get {
                return ResourceManager.GetString("Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        internal static string Modelo {
            get {
                return ResourceManager.GetString("Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo de Visualização.
        /// </summary>
        internal static string ModoDeVisualização {
            get {
                return ResourceManager.GetString("ModoDeVisualização", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alguns dispositivos não suportam múltiplas conexões Bluetooth. Deixe marcado essa opção se estiver tendo problemas de conexão..
        /// </summary>
        internal static string MultiplasConexoesDesc {
            get {
                return ResourceManager.GetString("MultiplasConexoesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        internal static string Não {
            get {
                return ResourceManager.GetString("Não", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Conectado.
        /// </summary>
        internal static string NãoConectado {
            get {
                return ResourceManager.GetString("NãoConectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NÃO CONECTADO A NENHUM DISPOSITIVO....
        /// </summary>
        internal static string NaoConectadoANenhumDispositivo {
            get {
                return ResourceManager.GetString("NaoConectadoANenhumDispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Conectado a Nenhum Dispositivo....
        /// </summary>
        internal static string NãoConectadoANenhumDispositivo {
            get {
                return ResourceManager.GetString("NãoConectadoANenhumDispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Detectado.
        /// </summary>
        internal static string NãoDetectado {
            get {
                return ResourceManager.GetString("NãoDetectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível enviar comando para um equipamento desconectado!.
        /// </summary>
        internal static string NãoÉPossívelEnviarComandoParaUmEquipamentoDesconectado {
            get {
                return ResourceManager.GetString("NãoÉPossívelEnviarComandoParaUmEquipamentoDesconectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível procurar!.
        /// </summary>
        internal static string NãoÉPossívelProcurar {
            get {
                return ResourceManager.GetString("NãoÉPossívelProcurar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário todas as plataformas estarem estáveis para enviar comandos!.
        /// </summary>
        internal static string NaoEstaEstavel {
            get {
                return ResourceManager.GetString("NaoEstaEstavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível ligar o adaptador Bluetooth.
        /// </summary>
        internal static string NãoFoiPossívelLigarOAdaptadorBluetooth {
            get {
                return ResourceManager.GetString("NãoFoiPossívelLigarOAdaptadorBluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível se registrar no serviço de Bluetooth.\nCaso a conexão não seja possível, favor ligar/desligar o modo avião, caso ainda não resolva, favor reiniciar o celular e tentar novamente...\nTentando novamente em 5 segundos....
        /// </summary>
        internal static string NaoFoiPossivelRegistrarBluetooth {
            get {
                return ResourceManager.GetString("NaoFoiPossivelRegistrarBluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há nenhum equipamento conectado para enviar comando....
        /// </summary>
        internal static string NãoHáNenhumEquipamentoConectadoParaEnviarComando {
            get {
                return ResourceManager.GetString("NãoHáNenhumEquipamentoConectadoParaEnviarComando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma Impressora Conectada.
        /// </summary>
        internal static string NenhumaImpressoraConectada {
            get {
                return ResourceManager.GetString("NenhumaImpressoraConectada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum Campo Personalizado.
        /// </summary>
        internal static string NenhumCampoPersonalizado {
            get {
                return ResourceManager.GetString("NenhumCampoPersonalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum equipamento conectado!.
        /// </summary>
        internal static string NenhumEquipamentoConectado {
            get {
                return ResourceManager.GetString("NenhumEquipamentoConectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Campo.
        /// </summary>
        internal static string NomeDoCampo {
            get {
                return ResourceManager.GetString("NomeDoCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da Empresa.
        /// </summary>
        internal static string NomeEmpresa {
            get {
                return ResourceManager.GetString("NomeEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Pesagem :.
        /// </summary>
        internal static string NºPesagem {
            get {
                return ResourceManager.GetString("NºPesagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesagem Nº.
        /// </summary>
        internal static string NumeroAnimal {
            get {
                return ResourceManager.GetString("NumeroAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero da rede da balança (Verificar etiqueta no módulo da balança).
        /// </summary>
        internal static string NumeroRedeBalancaDescricao {
            get {
                return ResourceManager.GetString("NumeroRedeBalancaDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observações.
        /// </summary>
        internal static string Observações {
            get {
                return ResourceManager.GetString("Observações", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opções Adicionais.
        /// </summary>
        internal static string OpçõesAdicionais {
            get {
                return ResourceManager.GetString("OpçõesAdicionais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTROS APLICATIVOS DA CELMI.
        /// </summary>
        internal static string OUTROSAPLICATIVOSDACELMI {
            get {
                return ResourceManager.GetString("OUTROSAPLICATIVOSDACELMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissões.
        /// </summary>
        internal static string Permissões {
            get {
                return ResourceManager.GetString("Permissões", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PESAGEM.
        /// </summary>
        internal static string PESAGEM {
            get {
                return ResourceManager.GetString("PESAGEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string PesagemAbreviada {
            get {
                return ResourceManager.GetString("PesagemAbreviada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesagem Armazenada com Sucesso!.
        /// </summary>
        internal static string PesagemArmazenadaComSucesso {
            get {
                return ResourceManager.GetString("PesagemArmazenadaComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesagem Dinâmica.
        /// </summary>
        internal static string PesagemDinâmica {
            get {
                return ResourceManager.GetString("PesagemDinâmica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesagem Salva.
        /// </summary>
        internal static string PesagemSalva {
            get {
                return ResourceManager.GetString("PesagemSalva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesagem Salva com Sucesso.
        /// </summary>
        internal static string PesagemSalvaComSucesso {
            get {
                return ResourceManager.GetString("PesagemSalvaComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesagens.
        /// </summary>
        internal static string Pesagens {
            get {
                return ResourceManager.GetString("Pesagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesagens importadas com sucesso....
        /// </summary>
        internal static string PesagensImportadasComSucesso {
            get {
                return ResourceManager.GetString("PesagensImportadasComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso 1.
        /// </summary>
        internal static string Peso1 {
            get {
                return ResourceManager.GetString("Peso1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso 2.
        /// </summary>
        internal static string Peso2 {
            get {
                return ResourceManager.GetString("Peso2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso 3.
        /// </summary>
        internal static string Peso3 {
            get {
                return ResourceManager.GetString("Peso3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso 4.
        /// </summary>
        internal static string Peso4 {
            get {
                return ResourceManager.GetString("Peso4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso 5.
        /// </summary>
        internal static string Peso5 {
            get {
                return ResourceManager.GetString("Peso5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso 6.
        /// </summary>
        internal static string Peso6 {
            get {
                return ResourceManager.GetString("Peso6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso 7.
        /// </summary>
        internal static string Peso7 {
            get {
                return ResourceManager.GetString("Peso7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso 8.
        /// </summary>
        internal static string Peso8 {
            get {
                return ResourceManager.GetString("Peso8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso Acumulado.
        /// </summary>
        internal static string PesoAcumulado {
            get {
                return ResourceManager.GetString("PesoAcumulado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso Bruto.
        /// </summary>
        internal static string PesoBruto {
            get {
                return ResourceManager.GetString("PesoBruto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso do Animal.
        /// </summary>
        internal static string PesoDoAnimal {
            get {
                return ResourceManager.GetString("PesoDoAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso Eixo 1.
        /// </summary>
        internal static string PesoEixo1 {
            get {
                return ResourceManager.GetString("PesoEixo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso Eixo 2.
        /// </summary>
        internal static string PesoEixo2 {
            get {
                return ResourceManager.GetString("PesoEixo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso Eixo 3.
        /// </summary>
        internal static string PesoEixo3 {
            get {
                return ResourceManager.GetString("PesoEixo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso Eixo 4.
        /// </summary>
        internal static string PesoEixo4 {
            get {
                return ResourceManager.GetString("PesoEixo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso Eixos.
        /// </summary>
        internal static string PesoEixos {
            get {
                return ResourceManager.GetString("PesoEixos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso Individual.
        /// </summary>
        internal static string PesoIndividual {
            get {
                return ResourceManager.GetString("PesoIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso Líquido.
        /// </summary>
        internal static string PesoLiquido {
            get {
                return ResourceManager.GetString("PesoLiquido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso (médio).
        /// </summary>
        internal static string PesoMédio {
            get {
                return ResourceManager.GetString("PesoMédio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso por Hectare:.
        /// </summary>
        internal static string PesoPorHectare {
            get {
                return ResourceManager.GetString("PesoPorHectare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso Total.
        /// </summary>
        internal static string PesoTotal {
            get {
                return ResourceManager.GetString("PesoTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plataforma.
        /// </summary>
        internal static string Plataforma {
            get {
                return ResourceManager.GetString("Plataforma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string PlataformaAbreviado {
            get {
                return ResourceManager.GetString("PlataformaAbreviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível salvar a pesagem se houver alguma plataforma desconectada. Aguarde a conexão de todas as plataformas e tente novamente..
        /// </summary>
        internal static string PlataformaDesconectadaSalvarErro {
            get {
                return ResourceManager.GetString("PlataformaDesconectadaSalvarErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plataformas.
        /// </summary>
        internal static string Plataformas {
            get {
                return ResourceManager.GetString("Plataformas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plataformas Detectadas.
        /// </summary>
        internal static string PlataformasDetectadas {
            get {
                return ResourceManager.GetString("PlataformasDetectadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plataformas Detectadas na Rede {0}.
        /// </summary>
        internal static string PlataformasOutraRede {
            get {
                return ResourceManager.GetString("PlataformasOutraRede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plataforma(s) Próxima(s).
        /// </summary>
        internal static string PlataformaSPróximaS {
            get {
                return ResourceManager.GetString("PlataformaSPróximaS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar Pesagens.
        /// </summary>
        internal static string popupBackup_CarregarBackup_ImportarPesagens {
            get {
                return ResourceManager.GetString("popupBackup_CarregarBackup_ImportarPesagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor selecione um Backup da Celmi.
        /// </summary>
        internal static string popupBackup_CarregarBackup_PorFavorSelecioneUmBackupDaCelmi {
            get {
                return ResourceManager.GetString("popupBackup_CarregarBackup_PorFavorSelecioneUmBackupDaCelmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesagens Excluidas!.
        /// </summary>
        internal static string popUpListagemOpcoes_Excluir_PesagensExcluidas {
            get {
                return ResourceManager.GetString("popUpListagemOpcoes_Excluir_PesagensExcluidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentual 1.
        /// </summary>
        internal static string Porcentual1 {
            get {
                return ResourceManager.GetString("Porcentual1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentual 2.
        /// </summary>
        internal static string Porcentual2 {
            get {
                return ResourceManager.GetString("Porcentual2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentual 3.
        /// </summary>
        internal static string Porcentual3 {
            get {
                return ResourceManager.GetString("Porcentual3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentual 4.
        /// </summary>
        internal static string Porcentual4 {
            get {
                return ResourceManager.GetString("Porcentual4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentual 5.
        /// </summary>
        internal static string Porcentual5 {
            get {
                return ResourceManager.GetString("Porcentual5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentual 6.
        /// </summary>
        internal static string Porcentual6 {
            get {
                return ResourceManager.GetString("Porcentual6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentual 7.
        /// </summary>
        internal static string Porcentual7 {
            get {
                return ResourceManager.GetString("Porcentual7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentual 8.
        /// </summary>
        internal static string Porcentual8 {
            get {
                return ResourceManager.GetString("Porcentual8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentual Eixo 1.
        /// </summary>
        internal static string PorcentualEixo1 {
            get {
                return ResourceManager.GetString("PorcentualEixo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentual Eixo 2.
        /// </summary>
        internal static string PorcentualEixo2 {
            get {
                return ResourceManager.GetString("PorcentualEixo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentual Eixo 3.
        /// </summary>
        internal static string PorcentualEixo3 {
            get {
                return ResourceManager.GetString("PorcentualEixo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentual Eixo 4.
        /// </summary>
        internal static string PorcentualEixo4 {
            get {
                return ResourceManager.GetString("PorcentualEixo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        internal static string Português {
            get {
                return ResourceManager.GetString("Português", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCURANDO....
        /// </summary>
        internal static string PROCURANDO {
            get {
                return ResourceManager.GetString("PROCURANDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurando Dispositivos....
        /// </summary>
        internal static string ProcurandoDispositivos {
            get {
                return ResourceManager.GetString("ProcurandoDispositivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCURAR.
        /// </summary>
        internal static string PROCURAR {
            get {
                return ResourceManager.GetString("PROCURAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produtor/Fazenda.
        /// </summary>
        internal static string ProdutorFazenda {
            get {
                return ResourceManager.GetString("ProdutorFazenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propriedade/Fazenda.
        /// </summary>
        internal static string PropriedadeFazenda {
            get {
                return ResourceManager.GetString("PropriedadeFazenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qtde Pesagens :.
        /// </summary>
        internal static string QtdePesagens {
            get {
                return ResourceManager.GetString("QtdePesagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de pesagens.
        /// </summary>
        internal static string QuantidadeDePesagens {
            get {
                return ResourceManager.GetString("QuantidadeDePesagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECONECTAR.
        /// </summary>
        internal static string RECONECTAR {
            get {
                return ResourceManager.GetString("RECONECTAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rede.
        /// </summary>
        internal static string Rede {
            get {
                return ResourceManager.GetString("Rede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatório Automotivo.
        /// </summary>
        internal static string RelatórioAutomotivo {
            get {
                return ResourceManager.GetString("RelatórioAutomotivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatório Aviação.
        /// </summary>
        internal static string RelatórioAviação {
            get {
                return ResourceManager.GetString("RelatórioAviação", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do Ensaio.
        /// </summary>
        internal static string RelatorioDadosDoEnsaio {
            get {
                return ResourceManager.GetString("RelatorioDadosDoEnsaio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatório de pesagem.
        /// </summary>
        internal static string RelatórioDePesagem {
            get {
                return ResourceManager.GetString("RelatórioDePesagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatório Ensaio de Campo.
        /// </summary>
        internal static string RelatórioEnsaioDeCampo {
            get {
                return ResourceManager.GetString("RelatórioEnsaioDeCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatório Geral.
        /// </summary>
        internal static string RelatórioGeral {
            get {
                return ResourceManager.GetString("RelatórioGeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatório Industrial.
        /// </summary>
        internal static string RelatórioIndustrial {
            get {
                return ResourceManager.GetString("RelatórioIndustrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatório Máquina Agrícola.
        /// </summary>
        internal static string RelatórioMáquinaAgrícola {
            get {
                return ResourceManager.GetString("RelatórioMáquinaAgrícola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observações :.
        /// </summary>
        internal static string RelatorioObservações {
            get {
                return ResourceManager.GetString("RelatorioObservações", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatório Pecurário.
        /// </summary>
        internal static string RelatórioPecurário {
            get {
                return ResourceManager.GetString("RelatórioPecurário", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso (total):.
        /// </summary>
        internal static string RelatorioPesoTotal {
            get {
                return ResourceManager.GetString("RelatorioPesoTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatórios.
        /// </summary>
        internal static string Relatórios {
            get {
                return ResourceManager.GetString("Relatórios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável.
        /// </summary>
        internal static string Responsável {
            get {
                return ResourceManager.GetString("Responsável", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurar Backup.
        /// </summary>
        internal static string RestaurarBackup {
            get {
                return ResourceManager.GetString("RestaurarBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sacas por Hectare:.
        /// </summary>
        internal static string SacasPorHectare {
            get {
                return ResourceManager.GetString("SacasPorHectare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salva automaticamente a pesagem  quando ocorrer estabilização da carga viva.
        /// </summary>
        internal static string SalvaCargaVivaDesc {
            get {
                return ResourceManager.GetString("SalvaCargaVivaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvando Pesagem.....
        /// </summary>
        internal static string SalvandoPesagem {
            get {
                return ResourceManager.GetString("SalvandoPesagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        internal static string Salvar {
            get {
                return ResourceManager.GetString("Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar ao estabilizar.
        /// </summary>
        internal static string SalvarAoEstabilizar {
            get {
                return ResourceManager.GetString("SalvarAoEstabilizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar Backup.
        /// </summary>
        internal static string SalvarBackup {
            get {
                return ResourceManager.GetString("SalvarBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleção.
        /// </summary>
        internal static string Seleção {
            get {
                return ResourceManager.GetString("Seleção", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selecionado(s).
        /// </summary>
        internal static string Selecionados {
            get {
                return ResourceManager.GetString("Selecionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione dispositivo para ver log específico!.
        /// </summary>
        internal static string SelecioneDispositivoParaVerLogEspecífico {
            get {
                return ResourceManager.GetString("SelecioneDispositivoParaVerLogEspecífico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem calibração.
        /// </summary>
        internal static string SemCalibração {
            get {
                return ResourceManager.GetString("SemCalibração", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        internal static string Sim {
            get {
                return ResourceManager.GetString("Sim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre.
        /// </summary>
        internal static string Sobre {
            get {
                return ResourceManager.GetString("Sobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente uma Conexão por Vez.
        /// </summary>
        internal static string SomenteUmaConexãoPorVez {
            get {
                return ResourceManager.GetString("SomenteUmaConexãoPorVez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status :.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substituir.
        /// </summary>
        internal static string Substituir {
            get {
                return ResourceManager.GetString("Substituir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUPORTE TÉCNICO.
        /// </summary>
        internal static string SUPORTETÉCNICO {
            get {
                return ResourceManager.GetString("SUPORTETÉCNICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tara.
        /// </summary>
        internal static string Tara {
            get {
                return ResourceManager.GetString("Tara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TELEFONES DE CONTATO.
        /// </summary>
        internal static string TELEFONESDECONTATO {
            get {
                return ResourceManager.GetString("TELEFONESDECONTATO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Pesagem.
        /// </summary>
        internal static string TipoDePesagem {
            get {
                return ResourceManager.GetString("TipoDePesagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de serviço.
        /// </summary>
        internal static string TipoDeServiCO {
            get {
                return ResourceManager.GetString("TipoDeServiCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Serviço.
        /// </summary>
        internal static string TipoDeServiço {
            get {
                return ResourceManager.GetString("TipoDeServiço", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total de Plataformas.
        /// </summary>
        internal static string TotalDePlataformas {
            get {
                return ResourceManager.GetString("TotalDePlataformas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trocar Logo.
        /// </summary>
        internal static string TrocarLogo {
            get {
                return ResourceManager.GetString("TrocarLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umidade.
        /// </summary>
        internal static string Umidade {
            get {
                return ResourceManager.GetString("Umidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Lido :.
        /// </summary>
        internal static string ValorLido {
            get {
                return ResourceManager.GetString("ValorLido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variedade.
        /// </summary>
        internal static string Variedade {
            get {
                return ResourceManager.GetString("Variedade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VENDAS.
        /// </summary>
        internal static string VENDAS {
            get {
                return ResourceManager.GetString("VENDAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver No Mapa.
        /// </summary>
        internal static string VerNoMapa {
            get {
                return ResourceManager.GetString("VerNoMapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versão.
        /// </summary>
        internal static string Versão {
            get {
                return ResourceManager.GetString("Versão", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zerar Acumulador.
        /// </summary>
        internal static string ZerarAcumulador {
            get {
                return ResourceManager.GetString("ZerarAcumulador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero.
        /// </summary>
        internal static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
    }
}
